
export enum IntentCode {
    // HISTORY - HPI
    ASK_CHIEF_COMPLAINT = 'ASK_CHIEF_COMPLAINT',
    ASK_ONSET = 'ASK_ONSET',
    ASK_DURATION = 'ASK_DURATION',
    ASK_CHARACTER = 'ASK_CHARACTER',
    ASK_RADIATION = 'ASK_RADIATION',
    ASK_ASSOCIATED_SYMPTOMS = 'ASK_ASSOCIATED_SYMPTOMS',
    ASK_EXACERBATING_FACTORS = 'ASK_EXACERBATING_FACTORS',
    ASK_RELIEVING_FACTORS = 'ASK_RELIEVING_FACTORS',
    ASK_SEVERITY = 'ASK_SEVERITY',
    ASK_DEMOGRAPHICS = 'ASK_DEMOGRAPHICS',

    // HISTORY - PAST
    ASK_PAST_MEDICAL_HISTORY = 'ASK_PAST_MEDICAL_HISTORY',
    ASK_MEDICATIONS = 'ASK_MEDICATIONS',
    ASK_ALLERGIES = 'ASK_ALLERGIES',
    ASK_SOCIAL_HISTORY = 'ASK_SOCIAL_HISTORY',
    ASK_FAMILY_HISTORY = 'ASK_FAMILY_HISTORY',

    // --- LIFESTYLE ---
    ASK_DIET = 'ASK_DIET',
    ASK_LIFESTYLE = 'ASK_LIFESTYLE',

    // --- PATIENT PERSPECTIVE (ICE) ---
    ASK_IDEAS = 'ASK_IDEAS',
    ASK_CONCERNS = 'ASK_CONCERNS',
    ASK_EXPECTATIONS = 'ASK_EXPECTATIONS',

    // --- MENTAL STATE EXAM (Psych) ---
    PERFORM_MSE_APPEARANCE = 'PERFORM_MSE_APPEARANCE',
    PERFORM_MSE_BEHAVIOR = 'PERFORM_MSE_BEHAVIOR',
    PERFORM_MSE_SPEECH = 'PERFORM_MSE_SPEECH',
    PERFORM_MSE_MOOD = 'PERFORM_MSE_MOOD',
    PERFORM_MSE_AFFECT = 'PERFORM_MSE_AFFECT',
    PERFORM_MSE_THOUGHT = 'PERFORM_MSE_THOUGHT',
    PERFORM_MSE_PERCEPTION = 'PERFORM_MSE_PERCEPTION',
    PERFORM_MSE_COGNITION = 'PERFORM_MSE_COGNITION',
    PERFORM_MSE_INSIGHT = 'PERFORM_MSE_INSIGHT',

    // GENERAL
    GREETING = 'GREETING',
    SOCIAL = 'SOCIAL',
    UNKNOWN = 'UNKNOWN',

    // EXAMINATION
    PERFORM_EXAM_GENERAL = 'PERFORM_EXAM_GENERAL',
    PERFORM_EXAM_CARDIO = 'PERFORM_EXAM_CARDIO',
    PERFORM_EXAM_RESP = 'PERFORM_EXAM_RESP',
    PERFORM_EXAM_ABDO = 'PERFORM_EXAM_ABDO',
    PERFORM_EXAM_NEURO = 'PERFORM_EXAM_NEURO',
    CHECK_VITALS = 'CHECK_VITALS',

    // INVESTIGATIONS
    REQUEST_ECG = 'REQUEST_ECG',
    REQUEST_LABS = 'REQUEST_LABS',
    REQUEST_IMAGING = 'REQUEST_IMAGING',
    REQUEST_TROPONIN = 'REQUEST_TROPONIN',

    // MANAGEMENT
    SUGGEST_MANAGEMENT = 'SUGGEST_MANAGEMENT',

    // HIGH LEVEL CATEGORIES (New System)
    CLINICAL_INTENT = 'CLINICAL_INTENT',
    SOFT_CLINICAL_INTENT = 'SOFT_CLINICAL_INTENT',
    CONVERSATIONAL_INTENT = 'CONVERSATIONAL_INTENT',
    UNCLEAR_INTENT = 'UNCLEAR_INTENT',
    NURSE_COMMAND = 'NURSE_COMMAND',
    
    // SAFETY
    SAFETY_ALERT = 'SAFETY_ALERT'
}

export interface IntentResult {
    intent: IntentCode;
    confidence: number;
    originalQuery: string;
}
